# Generated by Django 3.1 on 2020-09-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number_store',
            name='num',
            field=models.IntegerField(),
        ),
    ]
