# Generated by Django 3.0.5 on 2020-12-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_book', '0002_auto_20200903_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_store',
            name='topic',
            field=models.CharField(default='LongWay', max_length=30),
        ),
    ]
