# Generated by Django 3.0.5 on 2021-01-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_book', '0003_number_store_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_store',
            name='photo',
            field=models.ImageField(default='media/us.js', upload_to='gallery'),
        ),
    ]
