# Generated by Django 3.0.5 on 2021-01-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_book', '0004_number_store_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_store',
            name='photo2',
            field=models.ImageField(default='media/us.png', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='number_store',
            name='photo',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
