# Generated by Django 3.0.5 on 2021-01-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_book', '0005_auto_20210121_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number_store',
            name='photo2',
        ),
    ]
