# Generated by Django 3.0.5 on 2021-02-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_book', '0007_audio_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number_store',
            name='photo',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
